---
title: "Long-term Changes Surface Solar Shortwave Irradiance at Thessaloniki, Greece under clear- and all-sky conditions"
author:
  - Natsis Athanasios^[Laboratory of Atmospheric Physics, AUTH, natsisthanasis@gmail.com]
  - Alkiviadis Bais^[Laboratory of Atmospheric Physics, AUTH.]
  - Charikleia Meleti^[Laboratory of Atmospheric Physics, AUTH.]
  - Kleareti Tourpali^[Laboratory of Atmospheric Physics, AUTH.]
date: "`r format(Sys.time(), '%F')`"

documentclass: article
classoption:   a4paper,oneside
fontsize:      11pt
geometry:      "left=0.5in,right=0.5in,top=0.5in,bottom=0.5in"

bibliography:    [references.bib]
biblio-style:    apalike

header-includes:
- \usepackage{caption}
- \usepackage{placeins}
- \captionsetup{font=small}
- \usepackage{multicol}
- \setlength{\columnsep}{1cm}

output:
  bookdown::pdf_document2:
    number_sections:  no
    fig_caption:      no
    keep_tex:         no
    latex_engine:     xelatex
    toc:              yes
  html_document:
    keep_md:          yes
  odt_document:  default
  word_document: default

---

```{r include=FALSE, echo=FALSE}

####_  Document options _####

knitr::opts_chunk$set(echo       = FALSE   )
knitr::opts_chunk$set(cache      = TRUE    )
knitr::opts_chunk$set(include    = TRUE    )
knitr::opts_chunk$set(comment    = ""      )
# knitr::opts_chunk$set(dev        = "pdf"   )
knitr::opts_chunk$set(dev        = "png"   )

knitr::opts_chunk$set(fig.width  = 8       )
knitr::opts_chunk$set(fig.height = 6       )

knitr::opts_chunk$set(out.width  = "60%"    )
knitr::opts_chunk$set(fig.align  = "center" )
# knitr::opts_chunk$set(fig.pos    = '!h'     )
```



## Abstract

Measurements of downward shortwave solar irradiance are performed at Thessaloniki since 1993 with a Kipp & Zonen CM-21 pyranometer. Data are recorded as 1 min means and are quality controlled by adopting the procedure proposed by @long_automated_2008. The 26-year long time series is analysed in order to investigate long- and short-term changes caused by changes in atmospheric composition over the site. The overall increasing trend in daily solar irradiation under all-sky conditions of 0.33% per year reported for the period 1993–2012 [@Bais2013] is reconfirmed, although a stronger trend is calculated for the last decade of the data series.

An iterative optimization method has been employed to tune the clear-sky detection algorithm of @Reno2016 to the local conditions, in order to identify the cloud-free cases. A few simple global radiation models have been tested and adjustment factors for each model have been determined which match best the measured values.

Linear trends have been calculated for the entire period and different seasons for both clear- and all-sky conditions, in an attempt to attribute the long-term variability to variations in atmospheric water vapour and aerosols. Ancillary information from a collocated Cimel sun-photometer (since 2004), and a pyrheliometer (since 2016) are used to verify the effects of water vapor and aerosols on clear-sky irradiance. Finally, data under cloudy conditions are analysed to uncover potential effects from changes in cloudiness that have occurred over the period or record.
References






## Introduction

Radiation clouds trends

## Methodology

We process the 



Some aspects we have to study is the seasonality of the above finds
remove the sza dependence in order to see some local phenomena of the site




\ 
<!-- \vfill -->
\ 
